#!/usr/bin/python
# -*- coding:utf-8 -*-

from Tkinter import *
from changeInsUI import changeInsList
from changeAccUI import changeAccount
from changeDatabaseUI import changeDatabase
from getQueryUI import Query
from changeInsTimeUI import changeInsTime

master = Tk()
master.title('Getow')
#master.geometry('350x450')

def function1():
	tl = Toplevel()
def function2():
	changeInsList()
def function3():
	changeAccount()

buttonQuery = Button(master, text = "开始查询", command = Query)
buttonQuery.grid(padx = 80, pady = 20)

buttonChangeDatabase = Button(master, text = "修改数据库配置信息", command = changeDatabase)
buttonChangeDatabase.grid(padx = 80, pady = 20)

buttonChangeIns = Button(master, text= "修改订阅合约信息", command = changeInsList)
buttonChangeIns.grid(padx = 80, pady = 20)

buttonChangeInsTime = Button(master, text = "修改合约时间", command = changeInsTime)
buttonChangeInsTime.grid(padx = 80, pady = 20)

buttonChangeAccount = Button(master, text = "修改CTP账户", command = changeAccount)
buttonChangeAccount.grid(padx = 80, pady = 20)

buttonQuit = Button(master, text = "退出", command = quit)
buttonQuit.grid(padx = 80, pady = 20)

mainloop()
