#!/usr/bin/python
# -*- coding:utf-8 -*-

from Tkinter import *
from changeInsUI import changeInsList
from changeAccUI import changeAccount

master = Tk()
master.title('Getow')
#master.geometry('350x450')

def function1():
	tl = Toplevel()
def function2():
	changeInsList()
def function3():
	changeAccount()

buttonQuery = Button(master, text = "开始查询", command = function1)
buttonQuery.grid(padx = 80, pady = 20)

buttonChangeIns = Button(master, text= "修改订阅合约信息", command = function2)
buttonChangeIns.grid(padx = 80, pady = 20)

buttonChangeAccount = Button(master, text = "修改CTP账户", command = function3)
buttonChangeAccount.grid(padx = 80, pady = 20)

buttonQuit = Button(master, text = "退出", command = quit)
buttonQuit.grid(padx = 80, pady = 20)

mainloop()
